apiVersion: v1
kind: Service
metadata:
  name: express-qa
  namespace: quality-assurance
spec:
  selector:
    app: express
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer